import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Common/Navbar";
import BasicInfo from "./Components/Common/BasicInfo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="mytheme" lang="en">
      <body className={inter.className}>
        <div className="container  flex items-start  mx-auto justify-between  pb-24 pt-60 gap-8 max-w-[1200px] ">
          <BasicInfo />
          {children}
          <Navbar />
        </div>
      </body>
    </html>
  );
}
