import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Common/Navbar";
import BasicInfo from "./Components/Common/BasicInfo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="mytheme" lang="en">
      <body className={inter.className}>
        <div className="flex items-start max-w-screen-xl mx-auto justify-between py-[200px] gap-10">
          <BasicInfo />
          {children}
          <Navbar />
        </div>
      </body>
    </html>
  );
}
